server:
  port: 11001
spring:
  application:
    name: learning-vps
  redis:
    port: 6379
    host: 192.168.24.201
    password: 7777777
    timeout: 5000
#    database: 0

sms:
  # 昂网sms配置
  aw:
    server:
      url: http://47.104.84.72:8513/sms/Api/ReturnJson/Send.do
  # 9527sms配置
  nfts:
    server:
      url: http://120.76.228.10:8088/v2sms.aspx

my:
  auto:
    mybatis-plus:
      url: jdbc:mysql://localhost:3306/learning?useUnicode=true&autoReconnect=true
      username: wangxu
      password: wangxu
