#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#      insert-strategy: not_empty
#      update-strategy: not_empty
#      select-strategy: not_empty
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#  mapper-locations: classpath:mapper/*Mapper.xml

sharding-jdbc:
  prop:
    sqlShow: true
    executorSize: 4
    maxConnectionsSizePerQuery: 1

spring:
  datasource:
    druidSettingList:
      - url: jdbc:mysql://localhost:3306/learning1?useUnicode=true&autoReconnect=true
        username: wangxu
        password: wangxu
      - url: jdbc:mysql://localhost:3306/learning1?useUnicode=true&autoReconnect=true
        username: wangxu
        password: wangxu
      - url: jdbc:mysql://localhost:3306/learning2?useUnicode=true&autoReconnect=true
        username: wangxu
        password: wangxu
