server:
  port: 11101

spring:
  application:
    name: qrcode-server
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
#  mvc:
#    static-path-pattern: /static/**
