server:
  port: 10002

spring:
  application:
    name: es-server
  thymeleaf:
    cache: false

mybatis-plus:
  prop:
    pageLimitCount: 100

my:
  auto:
    mybatis-plus:
      url: jdbc:mysql://localhost:3306/learning?useUnicode=true&autoReconnect=true
      username: wangxu
      password: wangxu